/**
 * Scheduled headway lookup — the schedule-fallback data source.
 *
 * When realtime feeds return nothing, the display falls back to
 * "every ~N min (sched)" per route. Real timetables would cost megabytes;
 * this 7KB table (generated by scripts/generate-headways.mjs from NYC
 * subway static GTFS) carries typical trips-per-hour headways per
 * (route, dayType, hour).
 *
 * NYC subway only. The fallback is stateless per render cycle — the
 * moment a realtime fetch succeeds again, live data replaces it
 * automatically (see docs/DESIGN-v1.7.0.md #6).
 */

import headwaysJson from './packs/nyc-headways.json'

type DayType = 'wk' | 'sa' | 'su'
type HeadwayTable = Record<string, Record<DayType, Array<number | null>>>

const TABLE = headwaysJson as HeadwayTable

function dayTypeOf(date: Date): DayType {
  const d = date.getDay()
  if (d === 0) return 'su'
  if (d === 6) return 'sa'
  return 'wk'
}

/**
 * Typical scheduled headway in minutes for a route at the given time,
 * or null when the route has no scheduled service that hour (or is
 * unknown to the table).
 */
export function scheduledHeadway(route: string, date = new Date()): number | null {
  const entry = TABLE[route]
  if (!entry) return null
  return entry[dayTypeOf(date)][date.getHours()] ?? null
}
